/*
 * $Id: VTLParserResult.java 16 2010-01-07 02:34:45Z werner $
 *
 * Copyright (c) 2009 T-Systems International GmbH.
 * All rights reserved.
 * This software is the confidential and proprietary information
 * of T-Systems International GmbH.
 *
 */
package com.erudika.netbeans.velocity.parser;

import com.erudika.netbeans.velocity.jcclexer.VelocityParser;
import com.erudika.netbeans.velocity.jcclexer.node.SimpleNode;
import org.netbeans.modules.parsing.api.Snapshot;
import org.netbeans.modules.parsing.spi.ParseException;
import org.netbeans.modules.parsing.spi.Parser.Result;

/**
 * Represents result of parsing created for one specific {@link
 * VTLSyntaxErrorsHighlightingTask}.
 *
 * @author <a href="mailto:werner.jaeger@t-systems.com">Werner Jaeger</a>
 */
public class VTLParserResult extends Result
{
   private final VelocityParser m_Parser;
   private final SimpleNode m_ASTRoot;

   private boolean m_fValid;

   /**
    * Creates new {@code VTLParserResult} for the given snapshot.
    *
    * @param snapshot part of text to parse.
    * @param parser the actual parser generated by JavaCC.
    * @param astRoot the root of the parsed AST, or {@code null} if parsing failed.
    */
   VTLParserResult(final Snapshot snapshot, final VelocityParser parser, final SimpleNode astRoot)
   {
      super(snapshot);

      m_Parser = parser;
      m_ASTRoot = astRoot;
      m_fValid = true;
   }

   /**
    * Retrieves the actual parser instance.
    *
    * @return a reference to th parser instance actually use for parsing.
    *
    * @throws ParseException if this instance was {@link
    *         VTLParserResult#invalidate() invalidated}.
    */
   public VelocityParser getParser() throws ParseException
   {
      if (!m_fValid)
         throw new ParseException();

      return(m_Parser);
   }

   /**
    * Retrieves the root node of the parsed AST.
    *
    * @return the AST root, or {@code null} if parsing produced no AST.
    *
    * @throws ParseException if this instance was {@link
    *         VTLParserResult#invalidate() invalidated}.
    */
   public SimpleNode getAST() throws ParseException
   {
      if (!m_fValid)
         throw new ParseException();

      return m_ASTRoot;
   }

   /**
    * {@inheritDoc}
    */
   @Override protected void invalidate()
   {
      m_fValid = false;
   }
}
